spring.application.name=backend

server.port=${SERVER_PORT:8081}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/mydatabase?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.web=trace
logging.level.org.hibernate=trace
logging.level.com=TRACE
logging.file.name=/tmp/backend.log
app.security.migrate-plain-passwords=false
#logging.file.path=/Users/christianalvarezlobos/personal/Duoc/Desarrollo Instruccional/ISY2202/version2/backend